# Deep Learning Lab: Neural Network from Scratch



## Objective
Implement a Feedforward Neural Network from scratch.



### Neural Network Architecture
We'll build a 3-layer network:
- **Input layer**: 2 neurons
- **Hidden layer**: 3 neurons  
- **Output layer**: 1 neuron

### Forward Propagation
**Hidden layer:**
$$z_1 = X \cdot W_1 + b_1$$
$$a_1 = \sigma(z_1)$$

**Output layer:**
$$z_2 = a_1 \cdot W_2 + b_2$$
$$\hat{y} = \sigma(z_2)$$

### Activation Function
**Sigmoid:**
$$\sigma(x) = \frac{1}{1 + e^{-x}}$$

**Derivative:**
$$\sigma'(x) = \sigma(x) \cdot (1 - \sigma(x))$$

### Loss Function
**Mean Squared Error:**
$$MSE = \frac{1}{n} \sum (y - \hat{y})^2$$

### Backpropagation
Compute gradients using chain rule:
$$\frac{\partial L}{\partial W} = \frac{\partial L}{\partial \hat{y}} \cdot \frac{\partial \hat{y}}{\partial z} \cdot \frac{\partial z}{\partial W}$$

## Problem: XOR Function


| Input 1 | Input 2 | Output |
|---------|---------|--------|
| 0       | 0       | 0      |
| 0       | 1       | 1      |
| 1       | 0       | 1      |
| 1       | 1       | 0      |

In [1]:
# Import required library
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

print("Libraries imported successfully!")

Libraries imported successfully!


In [2]:
# Create XOR dataset
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

print("Input X:")
print(X)
print("\nOutput y:")
print(y)

Input X:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Output y:
[[0]
 [1]
 [1]
 [0]]


In [5]:
# Set hyperparameters
learning_rate = 0.1
epochs = 100

# Define network architecture
input_size = 2
hidden_size = 3
output_size = 1

print(f"Learning rate: {learning_rate}")
print(f"Epochs: {epochs}")
print(f"Architecture: {input_size} -> {hidden_size} -> {output_size}")

Learning rate: 0.1
Epochs: 100
Architecture: 2 -> 3 -> 1


In [6]:
# Initialize weights and biases
W1 = np.random.randn(input_size, hidden_size)  # 2x3 matrix
b1 = np.zeros((1, hidden_size))                 # 1x3 vector

W2 = np.random.randn(hidden_size, output_size)  # 3x1 matrix
b2 = np.zeros((1, output_size))                 # 1x1 scalar

print("Initial weights W1 (input to hidden):")
print(W1)
print("\nInitial bias b1:")
print(b1)
print("\nInitial weights W2 (hidden to output):")
print(W2)
print("\nInitial bias b2:")
print(b2)

Initial weights W1 (input to hidden):
[[ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]

Initial bias b1:
[[0. 0. 0.]]

Initial weights W2 (hidden to output):
[[-0.56228753]
 [-1.01283112]
 [ 0.31424733]]

Initial bias b2:
[[0.]]


In [7]:
# Define sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define sigmoid derivative
def sigmoid_derivative(x):
    return x * (1 - x)

# Test the functions
test_val = 0.5
print(f"sigmoid({test_val}) = {sigmoid(test_val)}")
print(f"sigmoid_derivative({test_val}) = {sigmoid_derivative(test_val)}")

sigmoid(0.5) = 0.6224593312018546
sigmoid_derivative(0.5) = 0.25


In [8]:
# Define loss function
def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Test with dummy data
dummy_true = np.array([[1], [0]])
dummy_pred = np.array([[0.9], [0.1]])
print(f"Test MSE: {mean_squared_error(dummy_true, dummy_pred):.4f}")

Test MSE: 0.0100


In [12]:
# Training loop
print("Starting training...")
print("="*80)

for epoch in range(epochs):
    # Forward propagation
    z1 = np.dot(X, W1) + b1      # Hidden layer input
    a1 = sigmoid(z1)              # Hidden layer output
    
    z2 = np.dot(a1, W2) + b2      # Output layer input
    y_pred = sigmoid(z2)          # Final prediction
    
    # Calculate loss
    loss = mean_squared_error(y, y_pred)
    
    # Backpropagation
    # Output layer gradients
    output_error = y_pred - y
    output_delta = output_error * sigmoid_derivative(y_pred)
    
    # Hidden layer gradients
    hidden_error = np.dot(output_delta, W2.T)
    hidden_delta = hidden_error * sigmoid_derivative(a1)
    
    # Compute weight gradients
    dW2 = np.dot(a1.T, output_delta)
    db2 = np.sum(output_delta, axis=0, keepdims=True)
    
    dW1 = np.dot(X.T, hidden_delta)
    db1 = np.sum(hidden_delta, axis=0, keepdims=True)
    
    # Update weights using gradient descent
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    
    # Print only loss (every epoch)
    print(f"Epoch {epoch + 1}/{epochs} - Loss: {loss:.6f}")

print("="*80)
print("Training completed!")
print("="*80)

# Print final weights and biases after training
print("\nFINAL WEIGHTS AND BIASES:")
print("="*80)
print("\nW1 (Input to Hidden):")
print(W1)
print("\nb1 (Hidden Layer Bias):")
print(b1)
print("\nW2 (Hidden to Output):")
print(W2)
print("\nb2 (Output Layer Bias):")
print(b2)

Starting training...
Epoch 1/100 - Loss: 0.241727
Epoch 2/100 - Loss: 0.241692
Epoch 3/100 - Loss: 0.241657
Epoch 4/100 - Loss: 0.241621
Epoch 5/100 - Loss: 0.241586
Epoch 6/100 - Loss: 0.241550
Epoch 7/100 - Loss: 0.241514
Epoch 8/100 - Loss: 0.241479
Epoch 9/100 - Loss: 0.241443
Epoch 10/100 - Loss: 0.241407
Epoch 11/100 - Loss: 0.241371
Epoch 12/100 - Loss: 0.241335
Epoch 13/100 - Loss: 0.241299
Epoch 14/100 - Loss: 0.241263
Epoch 15/100 - Loss: 0.241227
Epoch 16/100 - Loss: 0.241190
Epoch 17/100 - Loss: 0.241154
Epoch 18/100 - Loss: 0.241118
Epoch 19/100 - Loss: 0.241081
Epoch 20/100 - Loss: 0.241045
Epoch 21/100 - Loss: 0.241008
Epoch 22/100 - Loss: 0.240972
Epoch 23/100 - Loss: 0.240935
Epoch 24/100 - Loss: 0.240898
Epoch 25/100 - Loss: 0.240861
Epoch 26/100 - Loss: 0.240825
Epoch 27/100 - Loss: 0.240788
Epoch 28/100 - Loss: 0.240751
Epoch 29/100 - Loss: 0.240714
Epoch 30/100 - Loss: 0.240676
Epoch 31/100 - Loss: 0.240639
Epoch 32/100 - Loss: 0.240602
Epoch 33/100 - Loss: 0.24056

In [11]:
# Make final predictions
z1 = np.dot(X, W1) + b1
a1 = sigmoid(z1)
z2 = np.dot(a1, W2) + b2
final_predictions = sigmoid(z2)

print("="*80)
print("FINAL RESULTS")
print("="*80)
print("\nInput\t\tPredicted\tActual")
print("-" * 50)
for i in range(len(X)):
    pred = final_predictions[i][0]
    actual = y[i][0]
    pred_class = round(pred)
    print(f"{X[i]}\t{pred:.6f} ({pred_class})\t{actual}")

# Calculate accuracy
predicted_classes = np.round(final_predictions)
accuracy = np.mean(predicted_classes == y) * 100
print(f"\nAccuracy: {accuracy:.2f}%")

FINAL RESULTS

Input		Predicted	Actual
--------------------------------------------------
[0 0]	0.457614 (0)	0
[0 1]	0.522426 (1)	1
[1 0]	0.495364 (0)	1
[1 1]	0.524180 (1)	0

Accuracy: 50.00%
